// Do not edit!  This file was autogenerated 
// by the "C:\data\SRB2-marbycore-mod\comptime.bat" batch file 
// 
const char* compbranch = "Unknown"; 
const char* comprevision = "illegal"; 
const char* compnote = "Dummy"; 
